---
- name: Ensure project exists
  oc_project:
    name: ovn-kubernetes
    state: present
    node_selector:
      - ""

- name: Make temp directory for templates
  command: mktemp -d /tmp/ansible-XXXXXX
  register: mktemp
  changed_when: False

- name: Copy templates to temp directory
  copy:
    src: "{{ item }}"
    dest: "{{ mktemp.stdout }}/{{ item | basename }}"
  with_fileglob:
    - "files/*.yaml"
  when:
    - not ((item | basename == 'sdn-ovs.yaml') and openshift_use_external_openvswitch)

- name: Update the image tag
  yedit:
    src: "{{ mktemp.stdout }}/ovn-images.yaml"
    key: 'tag.from.name'
    value: "{{ ovn_image }}"

- name: Ensure the service account can run privileged
  oc_adm_policy_user:
    namespace: "ovn-kubernetes"
    resource_kind: scc
    resource_name: privileged
    state: present
    user: "system:serviceaccount:ovn-kubernetes:ovn"

# TODO: temporary until we fix apply for image stream tags
- name: Remove the image stream tag
  shell: >
    {{ openshift_client_binary }} delete -n ovn-kubernetes istag ovn-kubernetes:v3.11 --ignore-not-found

- name: Apply the config
  shell: >
    {{ openshift_client_binary }} apply -f "{{ mktemp.stdout }}"

- name: Remove temp directory
  file:
    state: absent
    name: "{{ mktemp.stdout }}"
  changed_when: False
