apiVersion: image.openshift.io/v1
kind: ImageStreamTag
metadata:
  name: ovn-kubernetes:v3.11
  namespace: ovn-kubernetes
tag:
  reference: true
  from:
    kind: DockerImage
    name: openshift3/ose-ovn-kubernetes:v3.11.0
